### ISSUE TITLE
Open source it! 

### ISSUE THREAD

**Issue by andrew** [librariesio/librarian#50]
Related to https://github.com/librariesio/libraries/issues/185

- [ ] License
- [ ] Contributing.md
- [ ] Code_of_conduct.md
- [ ] Setup docs in readme
- [ ] SECURITY.md
- [ ] Setup on travis-ci.org

**Comment by keithamus** [comment]
I think you can close this one @andrew :wink: :tada:

**Comment by andrew** [comment]
:dancer:
